import ContactForm from "/components/contactForm";
import GetCountry from "/components/getCountry";
import { getPackages } from "/sanity/sanity-utils";

export const metadata = {
  title: "Contact page metadata",
  description: "Generated by create next app",
};

const ContactPage = async () => {
  const packages = await getPackages(); //fetch places from sanity query can be fount in (sanity/sanity-utils.js)
  const indianPacks = packages.filter((pack) => {
    return pack.country && pack.country.includes("India");
  });
  const japanesePacks = packages.filter((pack) => {
    return pack.country && pack.country.includes("Japan");
  });
  const indianPackNames = indianPacks.map((item) => item.packageName);
  const japanesePackNames = japanesePacks.map((item) => item.packageName);

  return (
    <div className="container mt-0 md:mt-24">
      <h1 className="text-4xl font-bold my-4">Contact us</h1>
      <div className="grid grid-cols-1 sm:grid-cols-2">
        <div>content</div>
        <div className="flex justify-center">
          <ContactForm
            indianPackNames={indianPackNames}
            japanesePackNames={japanesePackNames}
          />
        </div>
      </div>
      <GetCountry country={null} />
    </div>
  );
};

export default ContactPage;
