import ContactForm from "/components/contactForm";
import GetCountry from "/components/getCountry";

export const metadata = {
  title: "Contact page metadata",
  description: "Generated by create next app",
};

const ContactPage = () => {
  return (
    <div className="container mt-0 md:mt-24">
      <h1 className="text-4xl font-bold my-4">Contact us</h1>
      <ContactForm />
      <GetCountry country={null} />
    </div>
  );
};

export default ContactPage;
