import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "../../components/navbar";

const montserrat = Montserrat({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Learn NextJS Frontend",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} min-h-screen`}>
        <div className=" bg-header-gradient"></div>
        <Navbar />
        <main className="p-4 flex justify-center">
          <div className="max-w-3xl">{children}</div>
        </main>
      </body>
    </html>
  );
}
