import { Outfit, Noto_Sans } from "next/font/google";
import "./globals.css";
import Footer from "/components/footer";
import Providers from "/components/providers";
import { CountryProvider } from "/contexts/countryContext";
import Navbar from "/components/Navbar";

const outfit = Outfit({
  weight: ["variable"],
  subsets: ["latin"],
  variable: "--font-headings",
  display: "swap",
});

const noto_sans = Noto_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-primary",
  display: "swap",
});

export const metadata = {
  title: "Niko Travels - Inprogress",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // passing font variables to global.css can be accessed there and used
    <html lang="en" className={`${outfit.variable} ${noto_sans.variable}`}>
      {/* main layout page */}
      <body className="bg-neutral-100 dark:bg-neutral-900">
        <Providers>
          <CountryProvider>
            <Navbar />
            <main className="min-h-[84vh] sm:min-h-[80vh] md:min-h-[78vh]">
              {children}
            </main>
            <Footer />
          </CountryProvider>
        </Providers>
      </body>
    </html>
  );
}
