export const metadata = {
  title: "About page metadata",
  description: "Generated by create next app",
};

const AboutPage = () => {
  return (
    <div className="container mt-0 md:mt-24">
      <h3 className="text-3xl font-bold my-4">About us</h3>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque
        voluptatum consequuntur officia animi delectus nihil quam, illo sed
        placeat distinctio eius cupiditate nam. Saepe pariatur, suscipit commodi
        obcaecati id sapiente.
      </p>
    </div>
  );
};

export default AboutPage;
